### ISSUE TITLE
About mapsforge_flutter: ^2.0.2

### ISSUE THREAD

**Issue by Daniel-Pincay** [mikes222/mapsforge_flutter#65]
Hello, I´m trying to get the current version that the repository shows but I didn´t found for pub. Can u Help me? In pub is only 2.0.1.

**Comment by baranacikgoz** [comment]
Repository is massively different than the pub version. You can use it like 
````
mapsforge_flutter:
    git:
       url: https://github.com/mikes222/mapsforge_flutter
       path: mapsforge_flutter
````
